[package]
edition = "2021"
name = "termifier-core"
version = "1.0.0"

[lib]
crate-type = ["cdylib"]
path = "lib/lib.rs"

[dependencies]
napi = { version = "2.10.16", default-features = false, features = ["napi4"] }
napi-derive = "2.10.1"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
